
export const FETCH_MOVIES = 'FETCH_MOVIES';
export const REMOVE_MOVIE = 'REMOVE_MOVIE';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const SELECT_MOVIES = 'SELECT_MOVIES';
export const CHANGE_PAGINATION = 'CHANGE_PAGINATION';
export const CHANGE_ITEMS_PAGINATION = 'CHANGE_ITEMS_PAGINATION';
